trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: GIT  # <-- Your Azure DevOps variable group name

stages:
  - stage: TerraformPlan
    displayName: "Terraform Plan"
    jobs:
      - job: Plan
        displayName: "Terraform Plan"
        steps:
          - checkout: self

          - script: |
              sudo apt-get update
              sudo apt-get install -y wget unzip
            displayName: "Install wget and unzip"

          - script: |
              wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
              unzip terraform_1.7.5_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: "Install Terraform"

          - script: |
              terraform init \
                -backend-config="resource_group_name=$(backend_resource_group_name)" \
                -backend-config="storage_account_name=$(backend_storage_account_name)" \
                -backend-config="container_name=$(backend_container_name)" \
                -backend-config="key=$(backend_key)"
            displayName: "Terraform Init"
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)

          - script: |
              terraform plan \
                -out=tfplan \
                -var "resource_group_name=$(resource_group_name)" \
                -var "location=$(location)"
            displayName: "Terraform Plan"
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)

          - publish: tfplan
            artifact: tfplan

  - stage: TerraformApply
    displayName: "Terraform Apply"
    dependsOn: TerraformPlan
    jobs:
      - job: Apply
        displayName: "Terraform Apply"
        steps:
          - checkout: self

          - download: current
            artifact: tfplan

          - script: |
              sudo apt-get update
              sudo apt-get install -y wget unzip
            displayName: "Install wget and unzip"

          - script: |
              wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
              unzip terraform_1.7.5_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: "Install Terraform"

          - script: |
              cp $(Pipeline.Workspace)/tfplan/tfplan ./tfplan
            displayName: "Copy tfplan to working directory"

          - script: |
              terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
